#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BookKeeper.Resource", IsApplication=true)]

namespace BookKeeper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040003
			public const int expense_number_array = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int expense_type_array = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int income_number_array = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int income_type_array = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int money_accounts_array = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int money_numbers_array = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int tax_array = 2130968582;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int all_entries_list_view = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int amount_edit = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int create_reports_button = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int date_display = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int date_select_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int description_edit = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int entry_left_column = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int entry_middle_column = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int entry_right_column = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int expenseRadioButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int incomeRadioButton = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int money_account_spinner = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int new_entry_button = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int radioGroup1 = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int save_button = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int show_all_entries_button = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int tax_spinner = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int type_spinner = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int activity_entry_list = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int activity_main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int activity_new_entry = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int entry_list_item = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f03000c
			public const int add_entry = 2130903052;
			
			// aapt resource value: 0x7f03000f
			public const int add_entry_text = 2130903055;
			
			// aapt resource value: 0x7f03000a
			public const int amount = 2130903050;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f03000e
			public const int choose_account = 2130903054;
			
			// aapt resource value: 0x7f03000d
			public const int choose_type = 2130903053;
			
			// aapt resource value: 0x7f030003
			public const int create_reports = 2130903043;
			
			// aapt resource value: 0x7f030006
			public const int date = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int description = 2130903047;
			
			// aapt resource value: 0x7f030005
			public const int expense = 2130903045;
			
			// aapt resource value: 0x7f030004
			public const int income = 2130903044;
			
			// aapt resource value: 0x7f030001
			public const int new_entry = 2130903041;
			
			// aapt resource value: 0x7f030010
			public const int pick_date = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int save_entry = 2130903057;
			
			// aapt resource value: 0x7f030002
			public const int show_all_entries = 2130903042;
			
			// aapt resource value: 0x7f03000b
			public const int tax = 2130903051;
			
			// aapt resource value: 0x7f030009
			public const int to_or_from_account = 2130903049;
			
			// aapt resource value: 0x7f030008
			public const int type = 2130903048;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
